kafka
yastrebow/mailSender pull request #2
Opened 2021-12-29 16:55 UTC by yastrebow

2021-12-29 19:35 UTC, MichaelDeyev requested changes

2021-12-29 19:35 UTC, MichaelDeyev commented on pom.xml
> +        </dependency>
а зачем зависимость на постгрес? разве вы используйте БД в данном МС?

2021-12-29 19:35 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/mailsender/MailSenderApplication.java
> +    }
Лучше убрать лишние пустые строки.

2021-12-29 19:35 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/mailsender/kafka/KafkaConsumer.java
> +@Service
Здесь, так как этот клас не выполняет сервисных функций (бизнес логики), лучше использовать @Component вместо @Service

2021-12-29 19:35 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/mailsender/kafka/KafkaConsumer.java
> +        System.out.println("Receive Message: " + message);
Вмето sout лучше использовать логгер

2021-12-29 19:35 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/mailsender/service/Impl/EmailSenderServiceImpl.java
> +public class EmailSenderServiceImpl {
Этот класс называется *Impl, но он ничего не имплементирует.
Сервисы лучше реализовывать через интерфейсы.

2021-12-29 19:35 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/mailsender/service/Impl/EmailSenderServiceImpl.java
> +        System.out.println("Email is ready to send");
Лучше использовать логгер

2022-01-02 15:49 UTC, yastrebow commented on pom.xml
> +        </dependency>
Мой косяк. Это я сначала у Лёши списал, думал, что удалю, если не понадобится, а потом забыл.

2022-01-02 15:51 UTC, yastrebow commented on src/main/java/ru/yastrebov/mailsender/MailSenderApplication.java
> +    }
Убрал

2022-01-02 15:52 UTC, yastrebow commented on src/main/java/ru/yastrebov/mailsender/kafka/KafkaConsumer.java
> +@Service
Сделал

2022-01-02 16:01 UTC, yastrebow commented on src/main/java/ru/yastrebov/mailsender/kafka/KafkaConsumer.java
> +        System.out.println("Receive Message: " + message);
Вроде где-то попадался вариант с логгером, поищу. А так, в основном, примеры все с sout-ом.

2022-01-02 16:12 UTC, yastrebow commented on src/main/java/ru/yastrebov/mailsender/kafka/KafkaConsumer.java
> +        System.out.println("Receive Message: " + message);
Сделал. Работает))

2022-01-02 16:13 UTC, yastrebow commented on src/main/java/ru/yastrebov/mailsender/service/Impl/EmailSenderServiceImpl.java
> +public class EmailSenderServiceImpl {
Делал через Интерфейс (оттуда и Impl). Началась ругань со стороны Идеи. Никак было не победить(( Сейчас сделал по-новой. Работает)))

2022-01-02 16:16 UTC, yastrebow commented on src/main/java/ru/yastrebov/mailsender/service/Impl/EmailSenderServiceImpl.java
> +        System.out.println("Email is ready to send");
Сделал вроде

2022-01-02 16:21 UTC, yastrebow commented on src/main/java/ru/yastrebov/mailsender/service/Impl/EmailSenderServiceImpl.java
> +        System.out.println("Email is ready to send");
Хотя не знаю, насколько здесь оно надо. "System.out.println("Email is ready to send");" я вставил для каких-то промежуточных целей, да забыл убрать(
А так вся инфа о сообщениях в консоли отображается и без этого. Так что я бы убрал эту строчку вообще.

2022-01-02 20:29 UTC, MichaelDeyev commented on src/main/java/ru/yastrebov/mailsender/service/Impl/EmailSenderServiceImpl.java
> +        Logger LOG = LoggerFactory.getLogger(EmailSenderServiceImpl.class);
Лучше использовать ломбоковскую аннотацию @Sl4j
она генерирует эту строку. и далее можно просто использовать log.info(...)

2022-01-02 20:29 UTC, MichaelDeyev commented on src/main/resources/application.yaml
> +      bootstrap-servers: localhost:8082
У кафки разве по умолчанию не 9092 порт?

2022-01-03 11:37 UTC, merged